language: python
python:
  - "3.5"
services:
  - docker
before_install:
  - mkdir coverage
  - chmod 777 coverage
install:
  - pip install codecov
env:
  global:
    - COMPOSE_FILE=docker-compose.yml:docker-compose-travis.yml
script:
  - docker-compose build
  - docker-compose run --name db -d db
  - docker-compose run vedetra flask test --coverage
after_success:
  - codecov
