language: python
python:
  - "3.5"
services:
  - docker
install:
  - docker-compose build
env:
  global:
    - COMPOSE_FILE=docker-compose.yml:docker-compose-travis.yml
script:
  - docker-compose run --name db -d db
  - docker-compose run vedetra flask test
