version: '3'
services:
  vedetra:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - web.env.sample
    depends_on:
      - "db"
  db:
    image: "postgres:11-alpine"
    restart: always
    env_file: db.env.sample
    expose:
      - 5432
