---
- hosts: all
  become: yes
  tasks:
  - name: Install Python 3
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - python3
      - python3-pip

  - name: Install virtualenv
    pip:
      name: virtualenv
  - name: Create virtualenv
    become: no
    pip:
      virtualenv: "/home/ubuntu/venv"
      virtualenv_python: python3
      requirements: "/vagrant/requirements.txt"