---
- hosts: all
  vars_files:
    - "vault.yml"
    - "vars.yml"
  tasks:
  - name: Crete product user
    become: yes
    user:
      name: vedetra
      shell: /bin/bash
  - name: Install Python 3
    become: yes
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - python3
      - python3-pip
      - libpq-dev
      - python3-psycopg2
  - name: Install virtualenv
    become: yes
    pip:
      name: virtualenv
  - name: Create virtualenv
    become: no
    pip:
      virtualenv: "/home/ubuntu/venv"
      virtualenv_python: python3
      requirements: "/vagrant/requirements.txt"
  - name: Install PostgreSQL
    become: yes
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - postgresql
      - postgresql-contrib
  - name: Create postgres role for product
    become: yes
    become_user: postgres
    postgresql_user:
      name: vedetra
      password: "{{ vedetra_postgres_pass }}"
      role_attr_flags: "LOGIN"
  - name: Create postgres database for product
    become: yes
    become_user: postgres
    postgresql_db:
      name: vedetra
      encoding: UTF-8
      owner: vedetra