"""empty message

Revision ID: f2a03b217000
Revises: c1815fd1d521
Create Date: 2019-03-24 19:57:10.584730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a03b217000'
down_revision = 'c1815fd1d521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('md5_mac', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('sensor_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_md5_mac'), 'detection', ['md5_mac'], unique=False)
    op.drop_index('ix_vehicle_detection_md5_mac', table_name='vehicle_detection')
    op.drop_table('vehicle_detection')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_detection',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('md5_mac', sa.VARCHAR(length=32), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('sensor_id', sa.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vehicle_detection_md5_mac', 'vehicle_detection', ['md5_mac'], unique=False)
    op.drop_index(op.f('ix_detection_md5_mac'), table_name='detection')
    op.drop_table('detection')
    # ### end Alembic commands ###
